pipeline {
    agent any //refer to pipeline syntax for other config
    stages {
        stage("Clean Up"){
            steps {
                deleteDir() //see pipeline basic steps for details
            }
        }
        stage("Clone Repo"){
            steps {
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git"
            }
        }
        stage("Build"){
            steps {
                dir(simple-java-maven-app) {
                    sh "mvn clean install"
                } //dir() this is to work inside the repo folder
            }
        }
        stage("Test"){
            steps {
                dir(simple-java-maven-app) {
                    sh "mvn test"
                }
            }
        }
    }
}